name = "all"
children = [
    "alumni",
    "cargo",
    "community",
    "compiler",
    "core",
    "crates-io",
    "devtools",
    "docs",
    "ides",
    "infra",
    "lang",
    "lang-shepherds",
    "libs",
    "mods",
    "production",
    "release",
    "rustdoc",
    "twir",
]

[people]
leads = []
members = []

[[lists]]
address = "all@rust-lang.org"

[[lists]]
address = "team@rust-lang.org"

[[lists]]
address = "underhanded@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]
