name = "all"

[people]
leads = []
members = []
include-all-team-members = true

[[lists]]
address = "all@rust-lang.org"

[[lists]]
address = "team@rust-lang.org"

[[lists]]
address = "underhanded@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]
