name = "all"
children = [
    "community",
    "compiler",
    "core",
    "devtools",
    "docs",
    "docs-peers",
    "infra",
    "lang",
    "lang-shepherds",
    "libs",
    "release",
    "rustdoc",
]

[people]
leads = []
members = []

[[lists]]
address = "all@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "team@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "underhanded@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-underhanded@googlegroups.com",
]

[[lists]]
address = "verification@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-verification@googlegroups.com",
]
