name = "alumni"

[people]
leads = []
members = [
    "aatch",
    "Gankro",
    "pcwalton",
    "huonw",
    "peschkaj",
    "dotdash",
    "bkoropoff",
    "brson",
    "erickt",
    "arielb1",
    "jseyfried",
    "edunham",
    "tomprince",
]

[website]
name = "Rust team alumni"
description = "enjoying a leisurely retirement"
