name = "alumni"

[people]
leads = []
members = [
    "Gankra",
    "Aatch",
    "Kimundi",
    "TimNN",
    "alercah",
    "arielb1",
    "birkenfeld",
    "bkoropoff",
    "booyaa",
    "brson",
    "bstrie",
    "dotdash",
    "dwijnand",
    "edunham",
    "erickt",
    "frewsxcv",
    "huonw",
    "jonathandturner",
    "jseyfried",
    "niconii",
    "pcwalton",
    "peschkaj",
    "rpjohnst",
    "solson",
    "tomprince",
    "whitequark",
    "wycats",
]

[website]
name = "Rust team alumni"
description = "enjoying a leisurely retirement"
weight = -1000
