name = "arewewebyet"
kind = "marker-team"

[people]
leads = []
members = [
    "ibraheemdev",
    "giraffate",
    "adriantombu",
    "LukeMathWalker",
    "marcoow",
    "Turbo87",
]

[[github]]
orgs = ["rust-lang"]
