name = "arm"
kind = "marker-team"

[people]
leads = []
members = [
    "JamieCunliffe",
    "Stammark",
    "joaopaulocarreiro",
    "raw-bin",
    "jacobbramley",
    "adamgemmell",
    "hug-dev",
]
