name = "book"
subteam-of = "lang-docs"

[people]
leads = ["carols10cents", "chriskrycho"]
members = [
    "carols10cents",
    "chriskrycho",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Book team"
description = "Maintains The Rust Programming Language book"
repo = "https://github.com/rust-lang/book"
