name = "cargo"
subteam-of = "devtools"

[people]
leads = ["nrc"]
members = [
    "alexcrichton",
    "dwijnand",
    "Eh2406",
    "ehuss",
    "joshtriplett",
    "nrc",
    "withoutboats",
    "wycats",
]

[permissions]
bors.cargo.review = true

[rfcbot]
label = "T-cargo"
name = "Cargo"
ping = "rust-lang/cargo"

[website]
name = "Cargo team"
description = "design and implementation of Cargo"
discord-invite = "https://discord.gg/aEbd4eT"
discord-name = "#cargo"

[[lists]]
address = "cargo@rust-lang.org"
