name = "cargo"

[people]
leads = ["nrc"]
members = [
    "alexcrichton",
    "dwijnand",
    "eh2406",
    "ehuss",
    "joshtriplett",
    "nrc",
    "withoutboats",
    "wycats",
]

[website]
name = "Cargo team"
description = "design and implementation of Cargo"

[[lists]]
address = "cargo@rust-lang.org"
access-level = "everyone"
