name = "clippy"
subteam-of = "devtools"

[people]
leads = ["Manishearth", "flip1995"]
members = [
    "llogiq",
    "killercup",
    "Manishearth",
    "oli-obk",
    "matthiaskrgr",
    "phansch",
    "mikerite",
    "flip1995",
    "mcarton",
    "camsteffen",
    "giraffate",
    "xFrednet",
]
alumni = ["ebroto", "yaahc"]

[permissions]
perf = true
bors.clippy.review = true
bors.rust.review = true

[[github]]
orgs = ["rust-lang"]

[website]
name = "Clippy team"
description = "Designing and implementing the Clippy linter"
zulip-stream = "clippy"

[[lists]]
address="clippy@rust-lang.org"
