name = "clippy"
subteam-of = "devtools"

[people]
leads = ["manishearth", "oli-obk"]
members = [
    "llogiq",
    "killercup",
    "manishearth",
    "oli-obk",
]

[website]
name = "Clippy"
description = "design and implementation of the Clippy linter"
discord-invite = "https://discord.gg/vNNtpyD"
discord-name = "#clippy"
