name = "cloud-compute"
kind = "marker-team"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "pietroalbini",
    "oli-obk",
    "JoelMarcey",
    "yaahc",
    "bjorn3",
]

[permissions]
dev-desktop = true

[[github]]
team-name = "cloud-compute-team"  # The name of the GitHub team (optional)
orgs = ["rust-lang"]
