name = "cloud-compute"
kind = "marker-team"

[people]
leads = []
members = [
    "Dajamante",
    "JoelMarcey",
    "nellshamrell",
    "ouz-a",
    "yaahc",
]

[permissions]
dev-desktop = true

[[github]]
team-name = "cloud-compute-team"  # The name of the GitHub team (optional)
orgs = ["rust-lang"]
