name = "codegen-c-maintainers"
subteam-of = "compiler"

[people]
leads = []
members = [
    "Amanieu",
    "tgross35"
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Codegen C Maintainers"
description = "Developing the C based backend for rustc"
repo = "https://github.com/rust-lang/rustc_codegen_c"
