name = "community-survey"
subteam-of = "community"

[people]
leads = ["rylev"]
members = [
    "nikomatsakis",
    "nrc",
    "rylev",
    "yaahc",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting the community survey"
repo = "https://github.com/rust-lang/surveys"

[[github]]
orgs = ["rust-lang"]
