name = "community-survey"
subteam-of = "community"

[people]
leads = ["nikomatsakis", "rylev"]
members = [
    "Manishearth",
    "nikomatsakis",
    "rylev",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting the community survey"

[[github]]
orgs = ["rust-lang"]
