name = "community"

[people]
leads = ["ashleygwilliams"]
members = [
    "skade",
    "manishearth",
    "sebasmagri",
    "badboy",
    "ashleygwilliams",
    "komaeda",
    "technetos",
    "jonathandturner",
]

[website]
name = "Community team"
description = "Coordination and supporting events, content creation, the RustBridge program, and the survey."
email = "community@rust-lang.org"
repo = "https://github.com/rust-community/team"
discord-invite = "https://discord.gg/KskHZGT"
discord-name = "#community-team"

[[lists]]
address = "community@rust-lang.org"
extra-teams = [
    "community-content",
    "community-events",
    "community-rustbridge",
    "community-survey",
]
extra-emails = [
    "rust-community@googlegroups.com",
]

[[lists]]
address = "community-team@rust-lang.org"
extra-teams = [
    "community-content",
    "community-events",
    "community-rustbridge",
    "community-survey",
]
extra-emails = [
    "rust-community@googlegroups.com",
]

[[lists]]
address = "reach@rust-lang.org"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "carols10cents",
    "aidanhs",
]
extra-emails = [
    "dhosfelt@mozilla.com",
]

[[lists]]
address = "rustbridge@rust-lang.org"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "arshiamufti",
]
