name = "community"

[people]
leads = ["ashleygwilliams"]
members = [
    "skade",
    "manishearth",
    "sebasmagri",
    "badboy",
    "booyaa",
    "ashleygwilliams",
    "oe",
    "technetos",
    "arshiamufti",
    "parrywinkle",
    "spacekookie",
    "flaki",
    "mattgathu",
    "celaus",
    "wezm",
    "bstrie",
    "jonathandturner",
]

[website]
name = "Community team"
description = "coordinating events, outreach, commercial users, teaching materials, and exposure"
email = "community@rust-lang.org"

[[lists]]
address = "community@rust-lang.org"
access-level = "everyone"
extra-emails = [
    "rust-community@googlegroups.com",
    "varma.sunjay@gmail.com",
]

[[lists]]
address = "community-team@rust-lang.org"
access-level = "everyone"
extra-emails = [
    "rust-community@googlegroups.com",
    "varma.sunjay@gmail.com",
]

[[lists]]
address = "reach@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "carols10cents",
    "aidanhs",
]
extra-emails = [
    "dhosfelt@mozilla.com",
]

[[lists]]
address = "rustbridge@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "arshiamufti",
]
