name = "community-survey"
subteam-of = "community"

[people]
leads = ["jonathandturner"]
members = [
    "jonathandturner",
    "Manishearth",
    "mgattozzi",
]

[website]
name = "Survey team"
description = "Running, analysing, and presenting the community survey."
