name = "community"

[people]
leads = ["ashleygwilliams"]
members = [
    "skade",
    "manishearth",
    "sebasmagri",
    "badboy",
    "ashleygwilliams",
    "oe",
    "technetos",
    "jonathandturner",
]

[website]
name = "Community team"
description = "coordination and supporting events, content creation, the RustBridge program, and the survey"
email = "community@rust-lang.org"
repo = "https://github.com/rust-community/team"
discord-invite = "https://discord.gg/KskHZGT"
discord-name = "#general"

[[lists]]
address = "community@rust-lang.org"
access-level = "everyone"
extra-emails = [
    "rust-community@googlegroups.com",
    "varma.sunjay@gmail.com",
]

[[lists]]
address = "community-team@rust-lang.org"
access-level = "everyone"
extra-emails = [
    "rust-community@googlegroups.com",
    "varma.sunjay@gmail.com",
]

[[lists]]
address = "reach@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "carols10cents",
    "aidanhs",
]
extra-emails = [
    "dhosfelt@mozilla.com",
]

[[lists]]
address = "rustbridge@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "ashleygwilliams",
    "arshiamufti",
]
