name = "community-rustbridge"
subteam-of = "community"

[people]
leads = ["diannasoriel"]
members = [
    "diannasoriel",
    "ashleygwilliams",
    "technetos",
    "arshiamufti",
    "spacekookie",
    "sebasmagri",
    "mattgathu",
]

[website]
name = "RustBridge team"
description = "Helping to bring underrepresented groups into Rust"
repo = "https://github.com/rustbridge/team"
discord-invite = "https://discord.gg/cj5HMXA"
discord-name = "#rustbridge"

[[github]]
orgs = ["rust-lang"]
