name = "compiler"

[people]
leads = ["nikomatsakis"]
members = [
    "cramertj",
    "eddyb",
    "estebank",
    "nagisa",
    "oli-obk",
    "petrochenkov",
    "pnkfelix",
    "nikomatsakis",
    "michaelwoerister",
    "varkor",
    "Zoxc",
]

[website]
name = "Compiler team"
description = "compiler internals, optimizations"

[[lists]]
address = "compiler@rust-lang.org"
access-level = "everyone"
extra-people = [
    "arielb1",
    "jseyfried",
]

[[lists]]
address = "compiler-team@rust-lang.org"
access-level = "everyone"
extra-people = [
    "arielb1",
    "jseyfried",
]
