name = "compiler-contributors"
subteam-of = "compiler"

[people]
leads = []
members = [
  "Centril",
  "davidtwco",
  "flodiebold",
  "lqd",
  "Mark-Simulacrum",
  "matklad",
  "matthewjasper",
  "nikic",
  "nnethercote",
  "scalexm",
  "spastorino",
  "tmandry",
  "wesleywiser",
  "Xanewok",
  "zackmdavis",
]

[permissions]
perf = true
crater = true
bors.rust.review = true

[github]
orgs = ["rust-lang", "rust-lang-nursery"]
extra-teams = ["compiler"]

[website]
name = "Compiler team contributors"
repo = "http://github.com/rust-lang/compiler-team"
description = "folks who contribute on a regular basis"
