name = "core"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "ashleygwilliams",
    "pietroalbini",
    "skade",
    "steveklabnik",
    "Manishearth",
]
alumni = [
    "nrc",
    "carols10cents",
    "nikomatsakis",
]

[permissions]
bors.rust.review = true
bors.team.review = true

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[rfcbot]
label = "T-core"
name = "Core"
ping = "rust-lang/core"

[website]
name = "Core team"
description = "Managing the overall direction of Rust, subteam leadership, and any cross-cutting issues"
email = "core@rust-lang.org"
weight = 1000

[[lists]]
address = "core@rust-lang.org"

[[lists]]
address = "core-private@rust-lang.org"

[[lists]]
address = "core-team@rust-lang.org"

[[lists]]
address = "user-logos@rust-lang.org"

[[lists]]
address = "legal@crates.io"

[[lists]]
address = "trademark@rust-lang.org"

[[lists]]
address = "mediation@rust-lang.org"
include-team-members = false
extra-people = [
    "Mark-Simulacrum",
    "aidanhs",
    "ashleygwilliams",
    "steveklabnik",
    "Manishearth",
]

[[lists]]
address = "accounting@rust-lang.org"
include-team-members = false
extra-people = [
    "ashleygwilliams",
]

# Temporary hacky way to create personal aliases. Ashley and Pietro urgently
# need an alias to continue their work setting up the Rust Foundation.
[[lists]]
address = "ashleygwilliams@rust-lang.org"
include-team-members = false
extra-people = ["ashleygwilliams"]
[[lists]]
address = "pietroalbini@rust-lang.org"
include-team-members = false
extra-people = ["pietroalbini"]

[[discord-roles]]
name = "core-team"
role-id = 442628744864202753
color = "#3498db"

