name = "core"

[people]
leads = []
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "alexcrichton",
    "ashleygwilliams",
    "carols10cents",
    "nikomatsakis",
    "steveklabnik",
    "wycats",
]

[website]
name = "Core team"
description = "Direction of the project, subteam leadership, cross-cutting concerns."
email = "core@rust-lang.org"
weight = 1000

[[lists]]
address = "core@rust-lang.org"

[[lists]]
address = "core-team@rust-lang.org"

[[lists]]
address = "user-logos@rust-lang.org"

[[lists]]
address = "legal@crates.io"

[[lists]]
address = "trademark@rust-lang.org"
include-team-members = false
extra-people = [
    "aturon",
    "nikomatsakis",
]
