name = "crates-io"

[people]
leads = ["ashleygwilliams", "sgrif"]
members = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "jtgeibel",
    "withoutboats",
    "joshtriplett",
    "ishitatsuyuki",
    "steveklabnik",
]

[website]
name = "Crates.io team"
description = "management of operations, development, and policies for crates.io"
discord-invite = "https://discord.gg/Rbq8W5K"
discord-name = "#crates-io"

[[lists]]
address = "help@crates.io"
access-level = "everyone"
include-team-members = false
extra-people = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "alexcrichton",
]

[[lists]]
address = "crates-io@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "carols10cents",
    "ashleygwilliams",
    "sgrif",
    "alexcrichton",
]

[[lists]]
address = "admin@crates.io"
access-level = "everyone"
include-team-members = false
extra-people = [
    "aturon",
    "alexcrichton",
]
