name = "devtools"

[people]
leads = []
members = []

[website]
page = "dev-tools"
name = "Dev tools team"
description = "Rust developer tools"
repo = "https://github.com/rust-dev-tools/dev-tools-team"
discord-invite = "https://discord.gg/sG23nSS"
discord-name = "#dev-tools"

[[lists]]
address = "dev-tools@rust-lang.org"
extra-teams = [
    "cargo",
    "clippy",
    "ides",
    "rustdoc",
    "wg-bindgen",
    "wg-debugging",
    "wg-rustfmt",
    "wg-rustup",
]

[[lists]]
address = "rust-dev-tools@rust-lang.org"

[[lists]]
address = "tools-team@rust-lang.org"
