name = "devtools"

[people]
leads = ["nrc"]
members = [
    "fitzgen",
    "japaric",
    "killercup",
    "manishearth",
    "nrc",
    "steveklabnik",
    "withoutboats",
]

[website]
name = "Dev tools team"
description = "Rust developer tools"

[[lists]]
address = "dev-tools@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "rust-dev-tools@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "tools-team@rust-lang.org"
access-level = "everyone"
