name = "devtools"

[people]
leads = []
members = []

[website]
name = "Dev tools team"
description = "Rust developer tools"
repo = "https://github.com/rust-dev-tools/dev-tools-team"
discord-invite = "https://discord.gg/sG23nSS"
discord-name = "#dev-tools"

[[lists]]
address = "dev-tools@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "rust-dev-tools@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "tools-team@rust-lang.org"
access-level = "everyone"
