name = "docker"
subteam-of = "infra"

[people]
leads = ["Muscraft"]
members = [
    "Kobzol",
    "Muscraft",
    "sfackler",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Docker team"
description = "Maintains the official Docker images published to Docker Hub"
repo = "https://github.com/rust-lang/docker-rust/"
