name = "docker"
subteam-of = "launching-pad"

[people]
leads = []
members = [
    "sfackler",
    "Muscraft",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Docker team"
description = "Maintains the official Docker images published to Docker Hub"
repo = "https://github.com/rust-lang/docker-rust/"
