name = "docs-rs-reviewers"
subteam-of = "docs-rs"

[people]
leads = []
members = [
    "GuillaumeGomez",
    "syphar",
]
alumni = [
    "Nemo157",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Docs.rs reviewers"
description = "Docs.rs team members responsible for reviews"
repo = "https://github.com/rust-lang/docs.rs"
zulip-stream = "t-docs-rs"
