name = "docs-peers"

[people]
leads = []
members = [
    "Havvy",
    "matthewjasper",
    "alercah",
    "marioidival",
    "projektir",
]

[website]
name = "Documentation peers"
description = "oversight of specific documentation, and coordination with the docs team"
