name = "docs"

[people]
leads = ["steveklabnik"]
members = [
    "steveklabnik",
    "GuillaumeGomez",
    "QuietMisdreavus",
    "frewsxcv",
    "rylev",
    "celaus",
]

[website]
page = "documentation"
name = "Documentation team"
description = "ensuring Rust has fantastic documentation"

[[lists]]
address = "docs@rust-lang.org"
extra-teams = ["reference"]

[[lists]]
address = "doc-team@rust-lang.org"
extra-teams = ["reference", "rust-by-example"]
