name = "docs"

[people]
leads = ["steveklabnik"]
members = [
    "steveklabnik",
    "GuillaumeGomez",
    "frewsxcv",
    "QuietMisdreavus",
]

[website]
name = "Documentation team"
description = "ensuring Rust has fantastic documentation"

[[lists]]
address = "docs@rust-lang.org"
access-level = "everyone"
extra-teams = ["docs-peers"]

[[lists]]
address = "doc-team@rust-lang.org"
access-level = "everyone"
extra-teams = ["docs-peers"]
