name = "foundation-board-project-directors"
subteam-of = "launching-pad"

[people]
leads = []
members = [
  "carols10cents",
  "JakobDegen",
  "rylev",
  "scottmcm",
  "spastorino",
]
alumni = [
  "cuviper",
  "Mark-Simulacrum",
  "tmandry",
  "yaahc",
]

[website]
name = "Foundation Board Project Directors"
description = "Charged with representing the project on the Board of the Rust Foundation"
email = "project-directors@rust-lang.org"

[[lists]]
address = "project-directors@rust-lang.org"
