name = "gsoc-contributors"
kind = "marker-team"

[people]
leads = []
members = [
    "Oneirical",
    "d-sonuga",
    "mav3ri3k",
    "s7tya",
    "FractalFir",
    "ding-young",
    "suaviloquence",
    "tiif",
    "shannmu"
]

[permissions]
dev-desktop = true

[[zulip-groups]]
name = "gsoc-contributors"
