name = "icebreakers-llvm"
kind = "marker-team"

[people]
leads = []
members = [
    "ayazhafiz",
    "camelid",
    "comex",
    "cuviper",
    "hdhoang",
    "henryboisdequin",
    "heyrutvik",
    "JOE1994",
    "jryans",
    "luqmana",
    "mmilenko",
    "nagisa",
    "nikic",
    "Noah-Kennedy",
    "SiavoshZarrasvand",
    "spastorino",
    "vertexclique",
    "higuoxing",
    "DianQK",
]
alumni = [
    "hanna-kruppe",
]
