name = "icebreakers-llvm"
marker-team = true

[people]
leads = []
members = [
    "hdhoang",
    "heyrutvik",
    "JOE1994",
    "jryans",
    "mmilenko",
    "nagisa",
    "nikic",
    "rkruppe",
    "SiavoshZarrasvand",
    "spastorino",
    "vertexclique",
    "vgxbj"
]
