name = "icebreakers-cleanup-crew"
kind = "marker-team"

[people]
leads = []
members = [
    "AminArria",
    "camelid",
    "chrissimpkins",
    "contrun",
    "DutchGhost",
    "ethanboxx",
    "HallerPatrick",
    "hdhoang",
    "hellow554",
    "h-michael",
    "KarlK90",
    "matheus-consoli",
    "mental32",
    "Noah-Kennedy",
    "pard68",
    "pierreN",
    "RobbieClarken",
    "robjtede",
    "SarthakSingh31",
    "senden9",
    "shekohex",
    "sinato",
    "spastorino",
    "turboladen",
    "woshilapin",
    "yerke",
    "nmccarty",
    "Redblueflame",
    "imtsuki",
    "elshize",
    "PeytonT",
    "RobertoSnap",
    "LeSeulArtichaut",
    "MAdrianMattocks",
    "kanru",
]
