name = "ides"
subteam-of = "devtools"

[people]
leads = ["Xanewok"]
members = [
    "alexheretic",
    "autozimu",
    "jasonwilliams",
    "LucasBullen",
    "matklad",
    "vlad20012",
    "Xanewok",
]
alumni = [
    "nrc",
]

[[github]]
orgs = ["rust-lang"]

[rfcbot]
label = "T-IDEs"
name = "IDEs and editors"
ping = "rust-lang/ides"

[website]
name = "IDEs and editors team"
description = "Developing IDEs, editors, and other development tools such as Racer and rust-analyzer"

[[lists]]
address = "ides@rust-lang.org"

[[lists]]
address = "editors@rust-lang.org"
