name = "ides"
subteam-of = "devtools"

[people]
leads = ["nrc", "Xanewok"]
members = [
    "alexheretic",
    "autozimu",
    "jasonwilliams",
    "LucasBullen",
    "matklad",
    "nrc",
    "vlad20012",
    "Xanewok",
]

[website]
name = "IDEs and editors team"
description = "IDEs, editors, and supporting tools such as Racer and the RLS"

[[lists]]
address = "ides@rust-lang.org"

[[lists]]
address = "editors@rust-lang.org"
