name = "infra"

[people]
leads = ["aidanhs"]
members = [
    "alexcrichton",
    "shepmaster",
    "aidanhs",
    "TimNN",
    "Mark-Simulacrum",
    "erickt",
    "kennytm",
    "ashleygwilliams",
    "sgrif",
    "pietroalbini",
]

[website]
name = "Infrastructure team"
description = "infrastructure supporting the Rust project itself: CI, releases, bots, metrics"
email = "infra@rust-lang.org"

[[lists]]
address = "infra@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "infra-team@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "craterbot@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "admin@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "aturon",
    "alexcrichton",
]

[[lists]]
address = "rust-key@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "aturon",
    "alexcrichton",
]

[[lists]]
address = "appveyor@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "appveyor-libs@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "bors@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-people = [
    "alexcrichton",
]

[[lists]]
address = "crates-io-cert@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "dmarc-rua@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]

[[lists]]
address = "docker-hub-rustci@rust-lang.org"
access-level = "everyone"
include-team-members = false
extra-emails = [
    "rust-ops@googlegroups.com",
]
