name = "infra"

[people]
leads = ["pietroalbini"]
members = [
    "Mark-Simulacrum",
    "jyn514",
    "kennytm",
    "pietroalbini",
    "shepmaster",
    "jdno",
    "rylev",
]
alumni = [
    "sgrif",
    "nellshamrell",
    "ashleygwilliams",
    "aidanhs",
]

[[github]]
orgs = ["rust-lang", "rust-lang-ci", "rust-lang-nursery"]

[[github]]
team-name = "rust-infra"
orgs = ["bors-rs"]

[permissions]
perf = true
crater = true
dev-desktop = true
bors.rust.review = true
bors.crater.review = true

[rfcbot]
label = "T-infra"
name = "Infrastructure"
ping = "rust-lang/infra"

[website]
name = "Infrastructure team"
description = "Managing the infrastructure supporting the Rust project itself, including CI, releases, bots, and metrics"
email = "infra@rust-lang.org"
zulip-stream = "t-infra"

[[lists]]
address = "infra@rust-lang.org"

[[lists]]
address = "infra-team@rust-lang.org"

[[lists]]
address = "craterbot@rust-lang.org"

[[zulip-groups]]
name = "T-infra"

[[discord-roles]]
name = "infra-team"
color = "#ff5454"
