name = "infra"
subteam-of = "operations"

[people]
leads = ["aidanhs", "pietroalbini"]
members = [
    "Mark-Simulacrum",
    "aidanhs",
    "alexcrichton",
    "ashleygwilliams",
    "kennytm",
    "pietroalbini",
    "sgrif",
    "shepmaster",
]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.crater.review = true

[rfcbot]
label = "T-infra"
name = "Infrastructure"
ping = "rust-lang/infra"

[website]
name = "Infrastructure team"
description = "infrastructure supporting the Rust project itself: CI, releases, bots, metrics"
email = "infra@rust-lang.org"
discord-invite = "https://discord.gg/AxXmxzN"
discord-name = "#infra"

[[lists]]
address = "infra@rust-lang.org"

[[lists]]
address = "infra-team@rust-lang.org"

[[lists]]
address = "craterbot@rust-lang.org"
