name = "lang"

[people]
leads = ["nikomatsakis"]
members = [
    "Centril",
    "aturon",
    "cramertj",
    "eddyb",
    "joshtriplett",
    "nikomatsakis",
    "nrc",
    "pnkfelix",
    "scottmcm",
    "withoutboats",
]

[website]
name = "Language team"
description = "designing new language features"

[[lists]]
address = "lang-private@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "lang@rust-lang.org"
access-level = "everyone"
extra-teams = ["lang-shepherds"]

[[lists]]
address = "language-design-team@rust-lang.org"
access-level = "everyone"
extra-teams = ["lang-shepherds"]
