name = "lang"

[people]
leads = ["nikomatsakis"]
members = [
    "cramertj",
    "withoutboats",
    "eddyb",
    "nrc",
    "pnkfelix",
    "nikomatsakis",
    "aturon",
    "joshtriplett",
    "scottmcm",
    "Centril",
]

[website]
name = "Language team"
description = "designing new language features"
