name = "library-reviewers"
subteam-of = "compiler"

[people]
leads = []
members = [
    "cramertj",
    "dtolnay",
    "joshtriplett",
    "kennytm",
    "KodrAus",
    "LukasKalbertodt",
    "m-ou-se",
    "Mark-Simulacrum",
    "sfackler",
    "shepmaster",
    "withoutboats",
]

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.rust.review = true
