name = "libs"

[people]
leads = ["alexcrichton"]
members = [
    "alexcrichton",
    "sfackler",
    "BurntSushi",
    "Kimundi",
    "SimonSapin",
    "dtolnay",
    "aturon",
    "KodrAus",
    "withoutboats",
]

[website]
name = "Library team"
description = "the Rust standard library, rust-lang crates, conventions, and ecosystem support"
