name = "libs"

[people]
leads = ["alexcrichton"]
members = [
    "Amanieu",
    "BurntSushi",
    "Kimundi",
    "KodrAus",
    "SimonSapin",
    "alexcrichton",
    "dtolnay",
    "sfackler",
    "withoutboats",
]

[github]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
perf = true
crater = true
bors.rust.review = true
bors.hashbrown.review = true
bors.libc.review = true
bors.stdarch.review = true

[rfcbot]
label = "T-libs"
name = "Libraries"
ping = "rust-lang/libs"
exclude-members = [
    "BurntSushi",
    "KodrAus",
]

[website]
page = "library"
name = "Library team"
description = "the Rust standard library, rust-lang crates, conventions, and ecosystem support"

[[lists]]
address = "libs-private@rust-lang.org"

[[lists]]
address = "libs@rust-lang.org"

[[lists]]
address = "library-team@rust-lang.org"
