name = "libs"

[people]
leads = ["alexcrichton"]
members = [
    "alexcrichton",
    "sfackler",
    "BurntSushi",
    "Kimundi",
    "SimonSapin",
    "dtolnay",
    "aturon",
    "KodrAus",
    "withoutboats",
]

[website]
name = "Library team"
description = "the Rust standard library, rust-lang crates, conventions, and ecosystem support"

[[lists]]
address = "libs-private@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "libs@rust-lang.org"
access-level = "everyone"

[[lists]]
address = "library-team@rust-lang.org"
access-level = "everyone"
