name = "mentors"
kind = "marker-team"
subteam-of = "mentorship"

[people]
leads = []
members = [
    "Kobzol",
    "jackh726",
    "Amanieu",
    "epage",
    "jieyouxu",
    "ytmimi",
    "oli-obk",
    "obi1kenobi",
    "davidlattimore"
]
alumni = []

[[zulip-groups]]
name = "gsoc-mentors"

[website]
name = "Mentorship Programs"
description = "Organizes involvement in internship programs such as Google Summer of Code"
