name = "mods-discourse"
subteam-of = "mods"

[people]
leads = []
members = [
    "technetos",
    "notriddle",
    "steffahn",
]
alumni = [
    "mbrubeck",
    "khionu",
]

[website]
name = "Discourse moderators"
description = "Moderating users.rust-lang.org and internals.rust-lang.org"

[[lists]]
address = "discourse-mods@rust-lang.org"
