name = "mods"

[people]
leads = []
members = [
    "mbrubeck",
    "BurntSushi",
    "niconii",
    "llogiq",
    "matthieu-m",
]

[website]
page = "moderation"
name = "Moderation team"
description = "helping uphold the code of conduct"
email = "rust-mods@rust-lang.org"

[[lists]]
address = "rust-mods@rust-lang.org"

[[lists]]
address = "mods@rust-lang.org"

[[lists]]
address = "mods-all@rust-lang.org"
extra-teams = [
    "mods-discord",
    "mods-discourse",
]
extra-people = ["Manishearth"] # Temporary, while we focus on trying to improve moderation and stuff