name = "mods"

[people]
leads = []
members = [
    "mbrubeck",
    "BurntSushi",
    "manishearth",
    "pnkfelix",
    "niconii",
    "llogiq",
    "matthieu-m",
]

[website]
name = "Moderation team"
description = "helping uphold the <a href='https://www.rust-lang.org/conduct.html'>code of conduct</a>"
email = "rust-mods@rust-lang.org"
