name = "project-edition-2024"
kind = "project-group"
subteam-of = "leadership-council"

[people]
leads = [
    "traviscross",
    "ehuss",
]
members = [
    "traviscross",
    "ehuss",
    "m-ou-se",
]
alumni = [
    "bstrie",
]

[[github]]
orgs = ["rust-lang"]
