name = "project-const-traits"
kind = "project-group"
subteam-of = "compiler"

[people]
leads = [
    "fee1-dead",
]
members = [
    "compiler-errors",
    "fee1-dead",
    "fmease",
    "oli-obk",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Const Traits Project Group"
description = "Project group working on const traits"
repo = "https://github.com/rust-lang/project-const-traits"
zulip-stream = "t-compiler/project-const-traits"
