name = "reference"
subteam-of = "docs"

[people]
leads = ["Havvy"]
members = [
    "Havvy",
    "matthewjasper",
    "alercah",
]

[website]
name = "Reference team"
description = "working on the rust reference"
