name = "reference"
subteam-of = "lang"

[people]
leads = ["ehuss"]
members = [
    "ehuss",
    "Havvy",
    "matthewjasper",
]
alumni = [
    "Centril",
]

[website]
name = "Reference team"
description = "Developing and writing the Rust reference"
zulip-stream = "t-lang.2Fwg-reference"
