name = "release"
subteam-of = "operations"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "Aaronepower",
    "alexcrichton",
    "ArazAbishov",
    "BatmanAoD",
    "Centril",
    "cuviper",
    "Dylan-DPC",
    "jkordish",
    "Mark-Simulacrum",
    "pietroalbini",
    "PramodBisht",
    "sgrif",
    "stokhos",
    "jonas-schievink",
]

[permissions]
crater = true
bors.rust.try = true

[website]
name = "Release team"
description = "tracking regressions, stabilizations, and producing Rust releases"
email = "release@rust-lang.org"
discord-invite = "https://discord.gg/pVTkgpv"
discord-name = "#release"

[[lists]]
address = "release@rust-lang.org"
