name = "release"

[people]
leads = ["Mark-Simulacrum"]
members = [
    "Mark-Simulacrum",
    "jrozner",
    "jkordish",
    "cuviper",
    "alexcrichton",
    "dirtybit",
    "Centril",
    "sgrif",
    "pietroalbini",
    "BatmanAoD",
    "PramodBisht",
    "ArazAbishov",
    "Aaronepower",
    "treiff",
    "cssivision",
    "stokhos",
]

[website]
name = "Release team"
description = "tracking regressions, stabilizations, and producing Rust releases"
email = "release@rust-lang.org"

[[lists]]
address = "release@rust-lang.org"
access-level = "everyone"
