name = "rust-analyzer-contributors"
subteam-of = "compiler"

[people]
leads = []
members = [
    "bjorn3",
    "edwin0cheng",
    "SomeoneToIgnore",
    "lowr",
    "HKalbasi",
]

[permissions]
bors.rust-analyzer.review = true

[[github]]
orgs = ["rust-lang", "rust-analyzer"]
