name = "rust-analyzer"
subteam-of = "compiler"

[people]
leads = ["Veykril"]
members = ["matklad", "lnicola", "Veykril", "flodiebold"]
alumni = ["jonas-schievink"]

[website]
name = "rust-analyzer team"
description = "Experimenting with a new compiler architecture tailored for IDEs"
zulip-stream = "t-compiler/rust-analyzer"

[permissions]
bors.rust.review = true
bors.rust-analyzer.review = true

[[github]]
orgs = ["rust-lang", "rust-analyzer"]
