name = "rustdoc"

[people]
leads = ["QuietMisdreavus"]
members = [
    "GuillaumeGomez",
    "QuietMisdreavus",
    "ollie27",
    "onur",
    "steveklabnik",
]

[website]
name = "Rustdoc team"
description = "Documentation tools including Rustdoc and docs.rs"

[[lists]]
address = "rustdoc@rust-lang.org"
access-level = "everyone"
