name = "rust-analyzer"
subteam-of = "compiler"

[people]
leads = ["Veykril"]
members = [
    "matklad",
    "lnicola",
    "Veykril",
    "flodiebold",
    "bjorn3",
    "lowr",
    "HKalbasi",
]
alumni = [
    "jonas-schievink",
    "edwin0cheng",
    "SomeoneToIgnore",
]

[website]
name = "rust-analyzer team"
description = "Rust IDE support and error-resilient compiler front-end"
zulip-stream = "t-compiler/rust-analyzer"

[permissions]
bors.rust.review = true
bors.rust-analyzer.review = true

[[github]]
orgs = ["rust-lang", "rust-analyzer"]

[[zulip-groups]]
name = "T-rust-analyzer"
