name = "rustlings"
subteam-of = "lang-docs"

[people]
leads = ["mo8it", "shadows-withal"]
members = [
    "shadows-withal",
    "mo8it",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustlings team"
description = "Maintains the Rustlings site"
repo = "https://github.com/rust-lang/rustlings/"
zulip-stream = "rustlings"
