name = "rustlings"
subteam-of = "lang-docs"

[people]
leads = ["mo8it", "manyinsects"]
members = [
    "manyinsects",
    "mo8it",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustlings team"
description = "Maintaining and updating the Rustlings course"
repo = "https://github.com/rust-lang/rustlings/"
zulip-stream = "t-lang/rustlings"
