name = "rustfmt"
subteam-of = "devtools"

[people]
leads = ["topecongiro", "calebcartwright"]
members = [
    "scampi",
    "topecongiro",
    "calebcartwright",
]
alumni = [
    "nrc",
]

[[github]]
orgs = ["rust-lang"]

[leads-permissions]
# Primarily for subtree syncs and other rustfmt-related review.
bors.rust.review = true

[website]
name = "Rustfmt team"
description = "Designing and implementing rustfmt, a formatting tool for Rust code"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustfmt"
