name = "rustup"
subteam-of = "devtools"

[people]
leads = [
    "kinnison",
    "rbtcollins",
]
members = [
    "kinnison",
    "rbtcollins",
    "hi-rustin",
]
alumni = [
    "nrc",
]

[website]
name = "Rustup team"
description = "Designing and implementing rustup"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustup"
