name = "social-media"
subteam-of = "launching-pad"

[people]
leads = ["m-ou-se"]
members = ["m-ou-se"]
alumni = []

[[lists]]
address = "social@rust-lang.org"

[website]
name = "Social media team"
description = "Handles posting on social media sites"
