name = "style"

[people]
leads = ["nrc"]
members = [
    "japaric",
    "joshtriplett",
    "nrc",
    "solson",
    "steveklabnik",
    "ubsan",
]

[[lists]]
address = "style-team@rust-lang.org"
access-level = "everyone"
