name = "twir-reviewers"
subteam-of = "twir"

[people]
leads = ["nellshamrell"]
members = [
    "nellshamrell",
    "cdmistman",
    "bennyvasquez",
    "ericseppanen",
    "extrawurst",
    "andrewpollack",
    "mariannegoldin",
    "U007D"
]

[[github]]
orgs = ["rust-lang"]
team-name = "twir-reviewers"
