name = "twir"
subteam-of = "launching-pad"

[people]
leads = ["nellshamrell"]
members = [
    "nellshamrell",
    "llogiq",
    "cdmistman",
    "extrawurst",
    "andrewpollack",
    "JoelMarcey",
]
alumni = [
    "nasa42",
]

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "twir@rust-lang.org"

[website]
name = "TWiR team"
description = "Publishes This Week in Rust"
repo = "https://github.com/rust-lang/this-week-in-rust"
