name = "twir"

[people]
leads = ["nellshamrell"]
members = [
    "nellshamrell",
    "llogiq",
    "cdmistman",
    "ericseppanen",
    "extrawurst",
    "andrewpollack",
    "U007D",
    "JoelMarcey",
]
alumni = [
    "nasa42",
]

[[lists]]
address = "twir@rust-lang.org"
