name = "types-fcp"
subteam-of = "types"

[people]
leads = []
members = [
    "BoxyUwU",
    "compiler-errors",
    "jackh726",
    "lcnr",
    "nikomatsakis",
    "oli-obk",
    "spastorino",
]
alumni = []

[rfcbot]
label = "T-types"
name = "Types"
ping = "rust-lang/types-fcp"

[website]
name = "Types FCP team"
description = "Types team members with responsibility for signing off on major compiler changes"
repo = "https://github.com/rust-lang/types-team"
zulip-stream = "t-types"
