name = "website"
subteam-of = "web-presence"

[people]
leads = ["Manishearth"]
members = [
    "Manishearth",
    "senekor",
]
alumni = [
    "XAMPPRocky",
    "skade",
    "pietroalbini",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Website team"
description = "Manages the www.rust-lang.org website"
repo = "https://github.com/rust-lang/www.rust-lang.org/"
