name = "website"
subteam-of = "web-presence"

[people]
leads = ["Manishearth"]
members = [
    "Manishearth",
]
alumni = [
    "XAMPPRocky",
    "skade",
    "pietroalbini",
]

[[github]]
orgs = ["rust-lang"]
