name = "wg-cli"
wg = true

[people]
leads = ["spacekookie"]
members = [
    "Dylan-DPC",
    "XAMPPRocky",
    "codesections",
    "epage",
    "killercup",
    "matthiasbeyer",
    "spacekookie",
    "yoshuawuyts",
]

[website]
page = "cli"
name = "Command-line interfaces (CLI) working group"
description = "Focusing on the end-to-end experience of writing terminal apps, both large and small, in Rust."

[[lists]]
address = "cli-wg@rust-lang.org"
