name = "wg-clippy"
wg = true

[people]
leads = ["llogiq", "killercup", "manishearth", "oli-obk"]
members = [
    "llogiq",
    "killercup",
    "manishearth",
    "oli-obk",
]

[website]
name = "Clippy working group"
description = "design and implementation of the Clippy linter"
discord-invite = "https://discord.gg/vNNtpyD"
discord-name = "#wg-clippy"
