name = "wg-compiler-performance"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikomatsakis"]
members = ["nikomatsakis"]

[website]
name = "Compiler performance working group"
description = "Improving rustc compilation performance (build times)"
