name = "wg-debugging"
subteam-of = "devtools"
kind = "working-group"

[people]
leads = ["Manishearth", "michaelwoerister"]
members = [
    "Manishearth",
    "michaelwoerister",
]

[website]
name = "Debugging working group"
description = "Developing and managing Rust debugging tools"
discord-invite = "https://discord.gg/UW3rnhd"
discord-name = "#wg-debugging"
