name = "wg-diagnostics"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["estebank", "oli-obk"]
members = ["davidtwco", "estebank", "JohnTitor", "oli-obk", "compiler-errors"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Diagnostics working group"
description = "Aiming to make rustc better at telling the user why the compiler isn't smart enough to understand their code yet"
repo = "https://rust-lang.github.io/compiler-team/working-groups/diagnostics/"
zulip-stream = "t-compiler/wg-diagnostics"
