name = "wg-embedded-infra"
subteam-of = "wg-embedded"
kind = "working-group"

[people]
leads = []
members = [
    "ryankurte",
    "nastevens",
]

[website]
name = "Embedded infrastructure team"
description = "Managing wg-embedded domains, DNS records, e-mails aliases, etc."

[[github]]
orgs = ["rust-embedded"]
team-name = "infrastructure"

