name = "wg-embedded"
wg = true

[people]
leads = ["japaric"]
members = [
    "japaric",
    "adamgreig",
    "andre-richter",
    "awygle",
    "bradjc",
    "cr1901",
    "danc86",
    "dvc94ch",
    "dylanmckay",
    "Emilgardis",
    "hannobraun",
    "ithinuel",
    "jamesmunns",
    "jcsoo",
    "korken89",
    "nastevens",
    "nerdyvaishali",
    "paoloteti",
    "parched",
    "pftbest",
    "posborne",
    "raw-bin",
    "ryankurte",
    "sekineh",
    "thejpster",
    "therealprof",
    "wizofe",
]

[website]
page = "embedded"
name = "Embedded devices working group"
description = "Focusing on the end-to-end experience of using Rust in resource-constrained environments and non-traditional platforms."

[[lists]]
address = "embedded-wg@rust-lang.org"
