name = "wg-embedded"
wg = true

[people]
leads = ["japaric"]
members = [
    "japaric",
    "adamgreig",
    "andre-richter",
    "awygle",
    "bradjc",
    "cr1901",
    "danc86",
    "dvc94ch",
    "dylanmckay",
    "Emilgardis",
    "hannobraun",
    "ithinuel",
    "jamesmunns",
    "jcsoo",
    "korken89",
    "nastevens",
    "nerdyvaishali",
    "paoloteti",
    "parched",
    "pftbest",
    "posborne",
    "raw-bin",
    "ryankurte",
    "sekineh",
    "thejpster",
    "therealprof",
    "wizofe",
]

[[lists]]
address = "embedded-wg@rust-lang.org"
access-level = "everyone"
extra-emails = [
    "david@craven.ch",
    "hanno@braun-robotics.com",
    "james.munns@gmail.com",
    "jcsoo@bobbin.io",
    "jp@thejpster.org.uk",
    "me@dylanmckay.io",
    "pftbest@gmail.com",
]
