name = "wg-embedded-resources"
subteam-of = "wg-embedded"
wg = true

[people]
leads = []
members = [
    "adamgreig",
    "andre-richter",
    "eldruin",
    "hargoniX",
    "jamesmunns",
    "therealprof",
]

[website]
name = "Embedded resources working group"
description = "Managing various resources owned by the embedded working group"

[[github]]
orgs = ["rust-lang"]
