name = "wg-gamedev"
wg = true

[people]
leads = ["AlexEne", "erlend-sh", "kvark"]

members = [
    "17cupsofcoffee",
    "AlexEne",
    "erlend-sh",
    "kvark",
    "ozkriff",
    "repi"
]

[website]
page = "gamedev"
name = "Game development working group"
description = "Focusing on making Rust the default choice for game development."
repo = "https://github.com/rust-gamedev"
discord-invite = "https://discord.gg/sG23nSS"
discord-name = "#wg-gamedev"

[[lists]]
address = "gamedev-wg@rust-lang.org"
