name = "wg-grammar"
subteam-of = "lang"
kind = "working-group"

[people]
leads = ["eddyb", "qmx"]
members = [
    "eddyb",
    "CAD97",
    "qmx",
]
alumni = [
    "Centril",
]

[website]
name = "Grammar working group"
description = "Working out the official, formal grammar for Rust and validating it against existing implementations"
