name = "wg-grammar"
subteam-of = "lang"
kind = "working-group"

[people]
leads = ["eddyb"]
members = [
    "eddyb",
    "CAD97",
   
]
alumni = [
    "Centril",
    "qmx",
]

[website]
name = "Grammar working group"
description = "Working out the official, formal grammar for Rust and validating it against existing implementations"
