name = "wg-incr-comp"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["pnkfelix", "wesleywiser"]
members = ["davidtwco", "pnkfelix", "spastorino", "wesleywiser", "michaelwoerister", "Aaron1011", "cjgillot", "pierwill"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Incremental compilation working group"
description = "Improving incremental compilation in rustc"
zulip-stream = "t-compiler/wg-incr-comp"

[permissions]
perf = true
bors.rust.try = true
