name = "wg-localization"
subteam-of = "community"
wg = true

[people]
leads = ["sebasmagri"]
members = [
    "sebasmagri",
    "Manishearth",
    "JohnTitor",
    "vertexclique",
]

[website]
name = "Localization WG"
description = "Working on localization of compiler, documentation and websites"
discord-invite = "https://discord.gg/cj5HMXA"
discord-name = "#community-team"
