name = "wg-llvm"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikic"]
members = [
    "nagisa",
    "nikic",
    "cuviper",
    "dianqk",
]
alumni = []

[[github]]
orgs = ["rust-lang"]

[website]
name = "LLVM working group"
description = "Working with LLVM upstream to represent Rust in its development"
repo = "https://rust-lang.github.io/compiler-team/working-groups/llvm/"
zulip-stream = "t-compiler/wg-llvm"
