name = "wg-learning"
subteam-of = "compiler"
wg = true

[people]
leads = ["nikomatsakis", "spastorino"]
members = ["nikomatsakis", "spastorino"]

[website]
name = "Learning"
description = "Make the compiler easier to learn by ensuring that rustc-guide and api docs are 'complete'"
repo = "https://github.com/rust-lang/compiler-team/blob/master/working-groups/learning"
