name = "wg-mir-opt"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["oli-obk"]
members = ["oli-obk", "eddyb", "davidtwco", "wesleywiser", "vertexclique", "JakobDegen"]
alumni = ["spastorino"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "MIR optimizations working group"
description = "Writing MIR optimizations and refactoring the MIR to be more optimizable"
repo = "https://rust-lang.github.io/compiler-team/working-groups/mir-opt/"
zulip-stream = "t-compiler/wg-mir-opt"

[permissions]
perf = true
bors.rust.try = true

[[zulip-groups]]
name = "WG-mir-opt"
