name = "wg-polonius"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["lqd", "nikomatsakis"]
members = ["lqd", "nikomatsakis", "albins", "matthewjasper"]

[website]
name = "Polonius working group"
description = "Working on an experimental new borrow-checker implementation"
repo = "https://rust-lang.github.io/compiler-team/working-groups/polonius/"

[[github]]
orgs = ["rust-lang"]
