name = "wg-prioritization"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["spastorino", "wesleywiser"]
members = [
    "am-1t",
    "apiraino",
    "bawerd",
    "camelid",
    "djcarpe",
    "Dylan-DPC",
    "frxstrem",
    "hameerabbasi",
    "JamesPatrickGill",
    "jechasteen",
    "JohnTitor",
    "jyn514",
    "lcnr",
    "LeSeulArtichaut",
    "mstallmo",
    "o0Ignition0o",
    "pnkfelix",
    "spastorino",
    "Stupremee",
    "tamuhey",
    "wesleywiser",
]
alumni = [
    "Centril",
    "mark-i-m",
]

[website]
name = "Prioritization working group"
description = "Triaging bugs, mainly deciding if bugs are critical (potential release blockers) or not"
repo = "https://rust-lang.github.io/compiler-team/working-groups/prioritization/"
zulip-stream = "t-compiler/wg-prioritization"

[[github]]
orgs = ["rust-lang"]
