name = "wg-polymorphization"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["davidtwco"]
members = ["davidtwco", "eddyb", "lcnr"]

[website]
name = "Polymorphization working group"
description = "Implementing polymorphization to reduce unnecessary monomorphisation in rustc"
repo = "https://rust-lang.github.io/compiler-team/working-groups/polymorphization/"
zulip-stream = "t-compiler.2Fwg-polymorphization"
