name = "wg-rust-analyzer"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["Veykril"]
members = ["matklad", "lnicola", "Veykril", "flodiebold"]
alumni = ["jonas-schievink"]

[website]
name = "rust-analyzer working group"
description = "Experimenting with a new compiler architecture tailored for IDEs"
repo = "https://rust-lang.github.io/compiler-team/working-groups/rust-analyzer/"
zulip-stream = "t-compiler/rust-analyzer"

[permissions]
bors.rust.review = true
bors.rust-analyzer.review = true

[[github]]
orgs = ["rust-lang", "rust-analyzer"]
