name = "wg-rustfmt"
subteam-of = "devtools"
wg = true

[people]
leads = ["topecongiro"]
members = [
    "scampi",
    "topecongiro",
]

[github]
orgs = ["rust-lang"]

[website]
name = "Rustfmt working group"
description = "design and implementation of Rustfmt"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustfmt"
