name = "wg-rustc-dev-guide"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["spastorino", "mark-i-m"]
members = ["spastorino", "mark-i-m", "amanjeev", "tshepang", "togiberlin", "JohnTitor", "chrissimpkins", "LeSeulArtichaut", "Nashenas88", "jyn514"]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustc Dev Guide working group"
description = "Make the compiler easier to learn by ensuring that rustc-dev-guide is \"complete\""
repo = "https://rust-lang.github.io/compiler-team/working-groups/rustc-dev-guide/"
zulip-stream = "t-compiler/wg-rustc-dev-guide"
