name = "wg-rls-2"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["matklad"]
members = ["matklad", "lnicola", "Veykril", "flodiebold", "jonas-schievink"]

[website]
name = "RLS 2.0 working group"
description = "Experimenting with a new compiler architecture tailored for IDEs"
repo = "https://rust-lang.github.io/compiler-team/working-groups/rls-2.0/"
zulip-stream = "t-compiler/wg-rls-2.0"

[permissions]
bors.rust.review = true
