name = "wg-rustfmt"
subteam-of = "devtools"
kind = "working-group"

[people]
leads = ["topecongiro"]
members = [
    "scampi",
    "topecongiro",
    "calebcartwright",
]
alumni = [
    "nrc",
]

[[github]]
orgs = ["rust-lang"]

[website]
name = "Rustfmt working group"
description = "Designing and implementing rustfmt, a formatting tool for Rust code"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustfmt"
