name = "wg-rustup"
subteam-of = "devtools"
wg = true

[people]
leads = [
    "alexcrichton",
    "kinnison",
    "nrc",
]
members = [
    "alexcrichton",
    "kinnison",
    "nrc",
]

[website]
name = "Rustup working group"
description = "design and implementation of Rustup"
discord-invite = "https://discord.gg/e6Q3cvu"
discord-name = "#wg-rustup"
