name = "wg-self-profile"
subteam-of = "compiler"
wg = true

[people]
leads = ["michaelwoerister", "wesleywiser"]
members = ["michaelwoerister", "wesleywiser"]

[permissions]
perf = true

[website]
name = "Self-Profile"
description = "Improving the -Z self-profile feature"
repo = "https://github.com/rust-lang/compiler-team/blob/master/working-groups/self-profile"
