name = "wg-traits"
subteam-of = "compiler"
wg = true

[people]
leads = ["nikomatsakis"]
members = ["nikomatsakis"]

[website]
name = "Traits"
description = "Revamping the rustc trait implementation to follow the Chalk approach."
repo = "https://github.com/rust-lang/compiler-team/tree/master/working-groups/traits"
