name = "wg-traits"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = ["nikomatsakis", "jackh726"]
members = [
    "Aaron1011",
    "Areredify",
    "detrumi",
    "flodiebold",
    "jackh726",
    "MarkMcCaskey",
    "Mcat12",
    "nathanwhit",
    "nikomatsakis",
    "skinny121",
    "yaahc",
    "zaharidichev",
]
alumni = [
    "scalexm",
    "tmandry",
]

[website]
name = "Traits working group"
description = "Revamping the rustc trait implementation to follow the Chalk approach"
repo = "https://rust-lang.github.io/compiler-team/working-groups/traits/"
zulip-stream = "wg-traits"

[[github]]
orgs = ["rust-lang", "rust-lang-nursery"]

[permissions]
bors.chalk.review = true
