name = "wg-wasm"
wg = true

[people]
leads = ["fitzgen"]
members = [
    "fitzgen",
    "alexcrichton",
    "aturon",
    "mgattozzi",
]

[[lists]]
address = "wasm@rust-lang.org"
access-level = "everyone"
