language: rust
rust: stable

script:
  - cargo run check
  - cargo run static-api build
  - echo "team-api.infra.rust-lang.org" > build/CNAME

deploy:
  provider: script
  script: curl -LsSf https://git.io/fhJ8n | rustc - && (cd build && ../rust_out)
  skip_cleanup: true
  on:
    branch: master
