allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
]

allowed-github-orgs = [
    "rust-lang",
    "rust-lang-ci",
    "rust-lang-nursery",
    "rust-dev-tools",
]
