allowed-mailing-lists-domains = [
    "rust-lang.org",
    "crates.io",
    "docs.rs",
    "rust-embedded.org",
]

allowed-github-orgs = [
    "bors-rs",
    "rust-lang",
    "rust-lang-ci",
    "rust-lang-nursery",
    "rust-dev-tools",
    "rust-embedded",
]
