[[lists]]
address = 'embedded-wg@rust-lang.org'
access_level = 'everyone'
members = [
  "david@craven.ch",
  "hanno@braun-robotics.com",
  "james.munns@gmail.com",
  "jcsoo@bobbin.io",
  "jorge@japaric.io",
  "jp@thejpster.org.uk",
  "me@dylanmckay.io",
  "pftbest@gmail.com",
]

[[lists]]
address = 'net@rust-lang.org'
access_level = 'everyone'
members = [
  "aturon@mozilla.com",
  "mark.simulacrum@gmail.com",
  "bob@cloudflare.com",
  "mail@josefbrandl.de",
  "tinagma@gmail.com",
  "coleman.mcfarland@gmail.com",
  "aidanhs@cantab.net",
  "dbarsky@amazon.com",
  "inejge@gmail.com",
  "bhargav.voleti93@gmail.com",
  "azdle@azdle.net",
  "yoshuawuyts@gmail.com",
  "aajtodd@gmail.com",
  "sfackler@gmail.com",
  "hello@stephanbuys.com",
  "wg-net@nemo157.com",
  "gruberbastian@me.com",
  "jsgf@fb.com",
  "mail@jakub-kozlowski.com",
  "michaeljkillough@gmail.com",
  "sloretan@gmail.com",
  "ashfordneil0@gmail.com",
  "a@tj.id.au",
  "yarnnd@gmail.com",
  "eric@reichertconsulting.com",
  "karimair@gmail.com",
  "flo@andersground.net",
  "rolf@zxcv.nl",
  "jbcden@gmail.com",
  "me@kleimkuhler.com",
  "pierre.krieger1708@gmail.com",
  "etryzelaar@google.com",
  "contact@geoffroycouprie.com",
  "eric@dattore.me",
  "service@maksims.co",
  "sriram@tinverse.com",
  "yusuke.sasaki.nuem@gmail.com",
  "ricky@hosfelt.io",
  "alberto@albertocoscia.me",
  "kulshrax@gmail.com",
  "alec@mocatta.net",
  "xenith@xenith.org",
  "arve.knudsen@gmail.com",
  "ben.e.saunders@gmail.com",
  "pickfire@riseup.net",
  "lkurusa@kernelstuff.org",
  "armin.ronacher@active-4.com",
]

[[lists]]
address = 'reach@rust-lang.org'
access_level = 'everyone'
members = [
  "ashley@integer32.com",
  "carol.nichols@integer32.com",
  "dhosfelt@mozilla.com",
  "aidanhs@cantab.net",
]

[[lists]]
address = 'rust-2018@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "nmatsakis@mozilla.com",
  "nrc@mozilla.com",
  "ashley@integer32.com",
  "mark.simulacrum@gmail.com",
  "twingoow@gmail.com",
  "mail@oli-obk.de",
  "killercup@gmail.com",
  "steve@steveklabnik.com",
  "japaricious@gmail.com",
  "fitzgen@mozilla.com",
  "aturon@mozilla.com",
]

[[lists]]
address = 'rust-icci@rust-lang.org'
access_level = 'everyone'
members = [
  "mwoerister@mozilla.com",
]

[[lists]]
address = 'rustbridge@rust-lang.org'
access_level = 'everyone'
members = [
  "ashley@integer32.com",
  "amufti16@gmail.com",
]

[[lists]]
address = 'twir@rust-lang.org'
access_level = 'everyone'
members = [
  "bogusandre@gmail.com",
  "vikrant@webstream.io",
]

[[lists]]
address = 'underhanded@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-underhanded@googlegroups.com",
]

[[lists]]
address = 'user-logos@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichton@mozilla.com",
  "wycats@gmail.com",
  "steve@steveklabnik.com",
  "dbau.pp@gmail.com",
  "aturon@mozilla.com",
  "nmatsakis@mozilla.com",
]

[[lists]]
address = 'verification@rust-lang.org'
access_level = 'everyone'
members = [
  "rust-verification@googlegroups.com",
]

[[lists]]
address = 'wasm@rust-lang.org'
access_level = 'everyone'
members = [
  "acrichto@mozilla.com",
  "aturon@mozilla.com",
  "mgattozzi@gmail.com",
]
