name = 'Rust timing data pusher'
github = 'rust-timer'
github-id = 12471139

[permissions]
# Needed for try builds and rollup=never, used to extract PRs from rollups to
# benchmark separately.
bors.rust.try = true
