name = "Igor Matuszewski"
github = "Xanewok"
github-id = 3093213
email = "xanewok@gmail.com"
zulip-id = 153740

[permissions]
bors.rls.review = true
bors.semverver.review = true
bors.vscode-rust.review = true
