org = 'rust-lang'
name = 'backtrace-rs'
description = 'Backtraces in Rust'
homepage = "https://docs.rs/backtrace"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[[branch-protections]]
pattern = 'master'
