org = "rust-lang"
name = "blog.rust-lang.org"
description = "Home of the Rust and Inside Rust blogs"
homepage = "https://blog.rust-lang.org"
bots = ["renovate"]

[access.teams]
inside-rust-reviewers = "write"
website = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = [
    "lint",
    "build",
]
