org = "rust-lang"
name = "cargo"
description = "The Rust package manager"
bots = ["bors", "rustbot"]

[access.teams]
cargo = "write"

[[branch-protections]]
pattern = "master"

[[branch-protections]]
pattern = "rust-1.*"
