org = "rust-lang"
name = "ci-mirrors"
description = "Upload files to Rust's CI mirrors"
homepage = "https://ci-mirrors.rust-lang.org"
bots = []

[access.teams]
infra = "write"

[[branch-protections]]
pattern = "main"
ci-checks = ["Build finished"]
dismiss-stale-review = true
