org = 'rust-lang'
name = 'flate2-rs'
description = 'DEFLATE, gzip, and zlib bindings for Rust'
homepage = "https://docs.rs/flate2"
bots = []

[access.teams]
crate-maintainers = 'maintain'

[[branch-protections]]
pattern = 'main'
