org = "rust-lang"
name = "nomicon"
description = "The Dark Arts of Advanced and Unsafe Rust Programming"
homepage = "https://doc.rust-lang.org/nomicon/"
bots = []

[access.teams]
lang = "write"
lang-docs = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["Success gate"]
