org = "rust-lang"
name = "project-const-traits"
description = "Const Traits Project Group"
homepage = "https://rust-lang.github.io/project-const-traits/"
bots = []

[access.teams]
project-const-traits = "maintain"
