org = "rust-lang"
name = "rust-analyzer"
description = "A Rust compiler front-end for IDEs"
bots = ["bors", "rustbot"]

[access.teams]
wg-rls-2 = "write"
wg-rls-2-triage = "triage"

[[branch]]
name = "master"
