org = "rust-lang"
name = "rust-log-analyzer"
description = "Analyzing Travis and Azure Pipelines logs to find encountered errors"
bots = []

[access.teams]
infra = "write"

[[branch-protections]]
pattern = "master"
ci-checks = ["CI"]
required-approvals = 0
