org = "rust-lang"
name = "rust-analyzer"
description = "A Rust compiler front-end for IDEs"
bots = ["bors", "rustbot"]

[access.teams]
wg-rust-analyzer = "write"
wg-rust-analyzer-contributors = "triage"

[[branch]]
name = "master"
