org = "rust-lang"
name = "rust-analyzer"
description = "A Rust compiler front-end for IDEs"
bots = ["bors", "rustbot"]

[access.teams]
rust-analyzer = "write"

[[branch-protections]]
pattern = "master"
