org = "rust-lang"
name = "rustc-stable-hash"
description = "A stable hashing algorithm used by rustc: cross-platform, deterministic, not secure"
bots = []

[access.teams]
compiler = "write"
compiler-contributors = "write"

[[branch-protections]]
pattern = "main"
