org = "rust-lang"
name = "rustc_codegen_gcc"
description = "libgccjit AOT codegen for rustc"
bots = []

[access.teams]
compiler = "write"
wg-gcc-backend = "maintain"

[[branch-protections]]
pattern = "master"
ci-checks = ["success"]
required-approvals = 0
