org = "rust-lang"
name = "team"
description = "Rust teams structure"
bots = ["bors", "highfive", "rustbot", "rust-timer"]

[access.teams]
core = "admin"
mods = "maintain"

[[branch]]
name = "master"
ci-checks = ["CI"]
dismiss-stale-review = true
