name = "community-ctcft"
subteam-of = "community"

[people]
leads = []
members = []
alumni = [
    "AngelOnFira",
    "nikomatsakis",
    "technetos",
    "yaahc"
]

[[github]]
orgs = ["rust-lang"]

[[lists]]
address = "ctcft@rust-lang.org"
