name = "project-error-handling"
kind = "project-group"
subteam-of = "libs"

[people]
leads = []
members = []
alumni = [
    "yaahc",
    "BurntSushi",
    "seanchen1991",
    "nagashi",
    "JDuchniewicz",
    "mystor",
    "senyosimpson",
]

[website]
name = "Error Handling Project Group"
description = "Identifying error handling best practices and consolidating the ecosystem"

[[github]]
orgs = ["rust-lang"]
