name = "wg-net-embedded"
subteam-of = "wg-net"
kind = "working-group"

[people]
leads = ["Nemo157", "levex"]
members = [
    "Nemo157",
    "levex",
]

[website]
name = "Embedded networking working group"
description = "Supporting IoT development with Rust"
discord-invite = "https://discord.gg/wUQwRea"
discord-name = "#wg-net-embedded"
