name = "wg-polymorphization"
subteam-of = "compiler"
kind = "working-group"

[people]
leads = []
members = []
alumni = ["davidtwco", "eddyb", "lcnr"]

[website]
name = "Polymorphization working group"
description = "Implementing polymorphization to reduce unnecessary monomorphisation in rustc"
repo = "https://rust-lang.github.io/compiler-team/working-groups/polymorphization/"
zulip-stream = "t-compiler/wg-polymorphization"

[[zulip-groups]]
name = "WG-polymorphization"
